name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build  # Uses vite.config.js's base: '/redbus-app/'

      - name: Add 404.html for SPA routing
        run: |
          cp public/404.html dist/
          echo "404.html added to dist/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN}}  # ✅ Correct key for PAT
          publish_dir: ./dist
          keep_files: true
